# Generated by Django 5.1 on 2024-08-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_card_added',
            field=models.BooleanField(default=False),
        ),
    ]
